<?php
return [
            'formStart' => '<form class="" {{attrs}}>',
            'label' => '<label{{attrs}}>{{text}}</label>',
            'input' => '<input class="form-control" type="{{type}}" name="{{name}}" {{attrs}} />',
            'select' => '<div><select name="{{name}}"{{attrs}}>{{content}}</select></div>',
            'inputContainer' => '<div class="form-group {{required}}" form-type="{{type}}">{{content}}</div>',
            'inputContainerError' => '<div class="form-group input {{type}}{{required}} error">{{content}}{{error}}</div>',
            'checkContainer' => '',
            'submitContainer' => '<div class="submit btn btn-default">{{content}}</div>',
            'button' => '<button{{attrs}} class="btn btn-default">{{text}}</button>',
            'checkboxContainer' => '<div class="checkbox">{{content}}</div>',
            'checkbox' => '<input type="checkbox" name="{{name}}" value="{{value}}"{{attrs}}>',
            'textarea' => '<textarea name="{{name}}"{{attrs}}>{{value}}</textarea>',
];
?>

<?php
// 93:             'button' => '<button{{attrs}}>{{text}}</button>',
// 94:             'checkbox' => '<input type="checkbox" name="{{name}}" value="{{value}}"{{attrs}}>',
// 95:             'checkboxFormGroup' => '{{label}}',
// 96:             'checkboxWrapper' => '<div class="checkbox">{{label}}</div>',
// 97:             'dateWidget' => '{{year}}{{month}}{{day}}{{hour}}{{minute}}{{second}}{{meridian}}',
// 98:             'error' => '<div class="error-message">{{content}}</div>',
// 99:             'errorList' => '<ul>{{content}}</ul>',
//100:             'errorItem' => '<li>{{text}}</li>',
//101:             'file' => '<input type="file" name="{{name}}"{{attrs}}>',
//102:             'fieldset' => '<fieldset{{attrs}}>{{content}}</fieldset>',
//103:             'formStart' => '<form{{attrs}}>',
//104:             'formEnd' => '</form>',
//105:             'formGroup' => '{{label}}{{input}}',
//106:             'hiddenBlock' => '<div style="display:none;">{{content}}</div>',
//107:             'input' => '<input type="{{type}}" name="{{name}}"{{attrs}}/>',
//108:             'inputSubmit' => '<input type="{{type}}"{{attrs}}/>',
//109:             'inputContainer' => '<div class="input {{type}}{{required}}">{{content}}</div>',
//110:             'inputContainerError' => '<div class="input {{type}}{{required}} error">{{content}}{{error}}</div>',
//111:             'label' => '<label{{attrs}}>{{text}}</label>',
//112:             'nestingLabel' => '{{hidden}}<label{{attrs}}>{{input}}{{text}}</label>',
//113:             'legend' => '<legend>{{text}}</legend>',
//114:             'multicheckboxTitle' => '<legend>{{text}}</legend>',
//115:             'multicheckboxWrapper' => '<fieldset{{attrs}}>{{content}}</fieldset>',
//116:             'option' => '<option value="{{value}}"{{attrs}}>{{text}}</option>',
//117:             'optgroup' => '<optgroup label="{{label}}"{{attrs}}>{{content}}</optgroup>',
//118:             'select' => '<select name="{{name}}"{{attrs}}>{{content}}</select>',
//119:             'selectMultiple' => '<select name="{{name}}[]" multiple="multiple"{{attrs}}>{{content}}</select>',
//120:             'radio' => '<input type="radio" name="{{name}}" value="{{value}}"{{attrs}}>',
//121:             'radioWrapper' => '{{label}}',
//122:             'textarea' => '<textarea name="{{name}}"{{attrs}}>{{value}}</textarea>',
//123:             'submitContainer' => '<div class="submit">{{content}}</div>',
?>